---
application:
  name: "cassandre-tech-production-trading-bot"
  project: "Cassandre-tech-production-trading-bot"
  organization: "QoveryCommunity"
databases:
- type: "POSTGRESQL"
  name: "cassandre-trading-bot"
  version: "12"
